config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items do
    collection do
      match 'search' => 'items#index', :via => [:get, :post], :as => :search
    end
  end

  resources :categories
  
  resources :genders

  root 'items#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
#  has_many   :feedbacks, :dependent => :destroy
  belongs_to :category
  belongs_to :gender
  belongs_to :user
  
  validates  :title,       presence: true,
                           length: { minimum: 3 }
  validates  :category_id, presence: true
  validates  :age,         presence: true
  validates  :gender_id,   presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
#  has_many :feedbacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_search

  def set_search
    @search=Item.search(params[:q])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :find_category, only: [:show, :edit, :update, :destroy]
#  before_filter :user_admin,    only: [:new, :edit, :update, :destroy]





  def index
    @categories = Category.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def destroy
    @category.destroy
    redirect_to categories_path  #action: "index"
  end

  def update
    if @category.update(categories_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end


  def create
    @categories = Category.new(categories_params)

    if @categories.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  private

#  def user_admin
#    redirect_to items_path if ((current_user == nil)||(current_user.is_admin == false))
#  end




  def find_category
    @category = Category.find(params[:id].to_i)
  end

  def categories_params
    params.require(:category).permit(:name_cat)
  end
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController

  before_filter :find_gender, only: [:show, :edit, :update, :destroy]
#  before_filter :user_admin,    only: [:new, :edit, :update, :destroy]

  def index
    @genders = Gender.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def destroy
    @gender.destroy
    redirect_to genders_path  #action: "index"
  end

  def update
    if @gender.update(genders_params)
      redirect_to genders_path
    else
      render 'edit'
    end
  end


  def create
    @genders = Gender.new(genders_params)

    if @genders.save
      redirect_to genders_path
    else
      render 'new'
    end
  end

  private

#  def user_admin
#    redirect_to items_path if ((current_user == nil)||(current_user.is_admin == false))
#  end

  def find_gender
    @gender = Gender.find(params[:id].to_i)
  end

  def genders_params
    params.require(:gender).permit(:name_gender)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item,          only: [:show, :edit, :update, :destroy]
#  before_filter :user_can_update,    only: [:edit, :update, :destroy]
#  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
#  before_filter :user_can_create,    only: [:new, :create]

  def index
    @search = Item.search(params[:q])
    @items = @search.result(:distinct => true).paginate(:page => params[:page], :per_page => 5)
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def update
    if ( current_user && ((current_user.is_admin == true)||(current_user == @item.user)))
      if @item.update(item_params)
        redirect_to @item
      else
        render 'edit'
      end
    else
      redirect_to items_path
    end
  end

  def destroy
    if ((current_user.is_admin == true)||(current_user == @item.user))
      @item.destroy
      redirect_to action: "index"
    else
      redirect_to items_path
    end
  end

  private

    def find_item   
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description, :user_id, :category_id, :gender_id, :name_cat, :name_gender, :age)
    end

#  private
#    def user_can_update
#      redirect_to items_path if ((current_user == nil)||(current_user.is_admin == false)||(current_user != @item.user))
#    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= form_for :category, url: category_path(@category), method: :patch do |f| %>

    <% if @category.errors.any? %>
        <dif id="error_explanation">
          <h2>
            <%= pluralize(@category.errors.count, "error") %> prohibited
            this categoty from being saved:
          </h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
          </dif>
    <% end %>

    <p>
      <%= f.label :name_cat %><br>
      <%= f.text_field :name_cat %>
    </p>


    <p>
      <%= f.submit %>
    </p>
<% end %>

<br/>
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table cols="3"  >
   <tr>
     <th width=80%></th>
     <th width="40px" ></th>
     <th width="40px" ></th>
   </tr>
  <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name_cat, category_path(category) %></td>
        <%# if (current_user != nil)&&(current_user.is_admin == true) %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category_path(category),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for Category.new do |f| %>


    <p>
      <%= f.label :name_cat %><br>
      <%= f.text_field :name_cat %>
    </p>


    <p>
      <%= f.submit %>
    </p>
<% end %>

<br/>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<i>Category</i>

  <h1><%= @category.name_cat %></h1>

<% @category.items.each do |item| %>
  <li><%= link_to item.title, item_path(item) %></li>
  
<% end %>

app/views/genders/edit.html.erb
<h1>Edit genders</h1>

<%= form_for :gender, url: gender_path(@gender), method: :patch do |f| %>

    <% if @gender.errors.any? %>
        <dif id="error_explanation">
          <h2>
            <%= pluralize(@gender.errors.count, "error") %> prohibited
            this gender from being saved:
          </h2>
          <ul>
            <% @gender.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
          </dif>
    <% end %>

    <p>
      <%= f.label :name_gender %><br>
      <%= f.text_field :name_gender %>
    </p>


    <p>
      <%= f.submit %>
    </p>
<% end %>

<br/>
<%= link_to 'Back', genders_path %>

app/views/genders/index.html.erb
<h1>Genders</h1>

<table cols="3"  >
   <tr>
     <th width=80%></th>
     <th width="40px" ></th>
     <th width="40px" ></th>
   </tr>
  <% @genders.each do |gender| %>
      <tr>
        <td><%= link_to gender.name_gender, gender_path(gender) %></td>
        <%# if (current_user != nil)&&(current_user.is_admin == true) %>
          <td><%= link_to 'Edit', edit_gender_path(gender) %></td>
          <td><%= link_to 'Destroy', gender_path(gender),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
  <% end %>
</table>

app/views/genders/new.html.erb
<h1>New gender</h1>

<%= form_for Gender.new do |f| %>


    <p>
      <%= f.label :name_gender %><br>
      <%= f.text_field :name_gender %>
    </p>


    <p>
      <%= f.submit %>
    </p>
<% end %>

<br/>
<%= link_to 'Back', genders_path %>

app/views/genders/show.html.erb
<i>Gender</i>

  <h1><%= @gender.name_gender %></h1>

<% @gender.items.each do |item| %>
  <li><%= link_to item.title, item_path(item) %></li>
  
<% end %>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= simple_form_for :item, url: item_path(@item), method: :patch do |f| %>

  <% if @item.errors.any? %>
    <dif id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

<br/>
    <p>
      <%= f.collection_select :category_id, Category.all, :id, :name_cat %>
    </p>
<br/>
    <p>
      <%= f.collection_select :gender_id, Gender.all, :id, :name_gender %>
    </p>
<br/>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<br/>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= search_form_for @search, url: search_items_path, method: :post do |f|  %>

  <div class="field">
    <%#= f.label :title_or_description_cont %><br />
    <b>Search: </b>
    <%= f.text_field :title_or_description_cont %>
    <%= f.label :age %>
    <%= f.select :age_eq, [nil, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] %>
    <%= f.submit "Search" %>
    <br />
    <%#= f.label :gender %>
    <%= f.collection_check_boxes :gender_id_eq_any, Gender.order(:name_gender), :id, :name_gender %>
    <br />
    <%#= f.label :category %>
    <%= f.collection_check_boxes :category_id_eq_any, Category.order(:name_cat), :id, :name_cat %>
  </div>
  

<% end %>
  <table cols="3"  >
    <tr>
      <th width="40%" align="center"> Title</th>
      <th width="50px" > Age </th>
      <th width="120px" > Created at </th>
      <th width="200px" > Cetegory </th>
      <th width="60px" > Genders </th>
      <th width="40px" ></th>
      <th width="40px" ></th>
    </tr>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.title, item_path(item) %></td>

        <td align="center"><%= item.age if item.age %></td>
        <td align="center"><%= item.created_at.strftime("%-d/%m/%y") %></td>
        <td align="center"><%= item.category.name_cat if item.category %></td>
        <td align="center"><%= item.gender.name_gender if item.gender %></td>
        <td align="center"><%= item.user.name if item.user %></td>
        <% if ((current_user != nil)&&(current_user.is_admin == true)) %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item_path(item),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

<br/>

<%= will_paginate @items %>

<br />

<div style="text-indent: 30px; font-size: 120%; font-weight: bold;">
  <%# if (current_user != nil)&&(current_user.is_admin == true) %>
    <%= link_to 'Add new item', new_item_path %>
  <%# end %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= simple_form_for Item.new do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <%= f.input :age, :collection => 1..16 %>

  <p>
    <%= f.label :choose_a_gender %><br>
    <%= f.association :gender, label_method: "#{:name_gender}", as: :radio_buttons %>
  </p>

  <p>
    <%= f.label :choose_a_category %><br>
    <%= f.association :category, label_method: "#{:name_cat}", as: :radio_buttons %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<br/>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
  <h2><%= @item.title %></h2>

  <i>Description:</i>
<p><%= @item.description %></p>


<i>Author:</i>
<p><%= @item.user ? @item.user.name : " " %></p>
<p><%= @item.gender.name_gender %> <i> Возраст: </i><%= @item.age %> <i>, Категория: </i><%= @item.category.name_cat %></p>

<hr>

<%# if current_user != nil %>
  <h3><%= 'Leave your feedback for this item' %></h3>
  <%#= form_for([@item, @item.reviews.build]) do |f| %>
    <p><%#= f.text_area :msg %></p>
    <p><%#= f.submit 'Create feedback' %></p>
  <%# end %>

  <%# else %>
  <%#= link_to 'Sign in for leave your feedback', new_user_session_path, method: :get %>
<%# end %>

<h3>Feedbacks</h3>
<%# @item.reviews.each do |review| %>

<%# if review.id != nil %>
  <p><%#= review.msg %><br/>
  <i><b>
  <%#= ( (review.user.name != "") ? review.user.name : review.user.email ) if review.user %>
  </b></i></p>
  <p>
  <%# if (current_user != nil)&&(current_user.is_admin == true) %>
    <%#= link_to 'Delete review', [review.item, review],
                 method:  :delete,
                 data: { confirm: 'Are you sure?' } %>
  <%# end %>    
  </p>
<%# end %>


<%# end %>

<br/>
<%= link_to 'Back to item list', items_path %>
<p>or</p>
<% if (current_user != nil)&&((current_user.is_admin == true)||(current_user == @item.user)) %>
  <%= link_to 'Edit', edit_item_path(@item) %>
  <%= link_to 'Delete', item_path(@item),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  <% else %>
  <%= link_to 'Sign in as Author for delete and edit the item', new_user_session_path, method: :get %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Child</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Child</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><a href="#">will be about...</a></li>
      </ul>


      <ul class="nav pull-right">   
        <li>
          <div id="user_nav">
            <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. Not you?
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger btn-mini' %>
            <% else %>
            <%= link_to new_user_registration_path do %>
            <button class="btn-mini btn btn-info">Sign Up</button>
            <% end %>
            or <%= link_to new_user_session_path do %>
            <button class="btn btn-info btn-mini">Sign In</button>
            <% end %>
            <% end %>
          </div>
        </li> 
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>






  <div class="container">
    <div class="row">
      <div class="col-xs-2">
        <%= link_to 'Complete list of items', items_path %>
        <br />
        <% Category.all.each do |category| %>
          <li><%= link_to category.name_cat, category_path(category) %></li>
        <% end %>
        <br />
        <% Gender.all.each do |gender| %>
          <li><%= link_to gender.name_gender, gender_path(gender) %></li>
        <% end %>
      </div>    
      <div class="col-xs-8"><%= yield %></div>
    </div>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>